### ISSUE TITLE
Documentation and Direction of Development for OpenAVRc

### ISSUE THREAD

**Issue by Tanmay-Mathur-Neuro** [pierrotm777/OpenAVRc_PM#1]
### Direction of Development of OpenAVRc

Hi Pierrot, 
First of all my hearty congratulation on achieving what OpenAVRc is so far, it is really Awesome, and would not be possible without the Hard-work  and persistence of the Devs and contributors. 
I have a few questions regarding this specific fork,   
1.  What are the new features/goals  for this fork of openAVRc? 
2. Is ExpressLRS a part of the intended development? 
3. How can i contribute to it? 

My background is of Embedded and hardware development, but nowhere as hardcore as you. Although I would like to experiment with this project and with little guidance I might be able to contribute something worthy. 
Apart from that, I have a functional transmitter that I am planning to document for DIY Guide on platforms like YouTube and RcGroups.org and then I am willing to take the documentation part as well maybe. 
Thanks!

**Comment by pierrotm777** [comment]
Welcome on OpenAVRc,
1. OpenAVRc is an OpenTx fork very optimised for an Atmega 2560 CPU.
2. Yes, we try to adapt Elrs/CRSF protocol but we have no time actually for that.
Actually, our CRSF protocol is ready to use a Tx Elrs or TBS modules, but we have no time for add config option:
- Rate option
- Telemetry option
- etc...
3. You are welcome in our team if you need time for develop with us OpenAVRc and add new protocols or features.
4. Please, use the Rcroups forum for speak about [OpenAVRc](https://www.rcgroups.com/forums/showthread.php?2968263-OpenAVRc-Solution-%28M2560%29-%28OPENTX%29-%28NEXTSTPRCV2-18-%29).
PM me your email in this forum.
We have a specific builder for work on OpenAVRc which use Code::Block .
If you have  some pictures about your OpenAVRc, send us your pictures for add them to our github.
Pierre

**Comment by pierrotm777** [comment]
Close, not issie

**Comment by Tanmay-Mathur-Neuro** [comment]
No worries!
Thanks for the elaborate reply.

Finest Regards,
Tanmay M
NeuroEquilibrium Diagnostics Pvt. Ltd.

**Comment by pierrotm777** [comment]
I need your email for speak with you about openavrc development. Can you send me your email on rcgroups please?
